server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dinesh-Mane/config-server-repo
#          uri: https://github.com/Dinesh-Mane/microservices-based-employee-management-system
          clone-on-start: true
          default-label: main
          search-paths: config-files

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka